name: docs

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
    paths: [ '**.java' ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.8  # wpilib 2021 jdk version
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Build with Gradle
        run: ./gradlew javadoc
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
          user_name: 'Boba Bots 253'
          user_email: 'noreply@bobabots253.com'
          commit_message: ${{ github.event.head_commit.message }}
